### ISSUE TITLE
Results are not appearing for predictions onuser-supplied sequences

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/TF-DNA-PredictionsDB#118]
After running predictions, the heatmap appears and the max value is displayed, but the detailed results are not displayed

![screen shot 2016-11-07 at 2 04 48 pm](https://cloud.githubusercontent.com/assets/2752599/20071629/369abf8a-a4f3-11e6-8a72-119eac45cf7e.png)

![screen shot 2016-11-07 at 2 03 35 pm](https://cloud.githubusercontent.com/assets/2752599/20071602/1664997a-a4f3-11e6-93d6-e985a262e56a.png)

**Comment by dleehr** [comment]
For example https://imads.genome.duke.edu/prediction?model=c-Myc_0001&selectedSequence=068eea72-a51c-11e6-abcb-0242ac120003&all=true

The database does have data for this, but it's not showing:

`select * from custom_result_row where result_id in (select id from custom_result where job_id in (select id from job where seq_id = '068eea72-a51c-11e6-abcb-0242ac120003'));`

**Comment by johnbradley** [comment]
This has been pushed to production and resolved.
