### ISSUE TITLE
Additional Binding Site Changes

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/TF-DNA-PredictionsDB#143]
Additional changes requested. Mainly changing verbiage and minor column changes.

>1. For SEARCH GENOME with a gene list:
>
>"Name, ID, Genomic region coordinates, Maximum iMADS score (One line per region)"
>"Name, ID, Genomic region coordinates, iMADS scores for all positions in region (One line per >region)”  (so no max value here)
>"Name, ID, Binding site coordinates, Binding site iMADS score, Binding site sequence (One line per site)”
>
>* here the genomic region coordinates could be in the standard format (chr?:?-?) rather than on 3 columns.
>* I changed Max to Maximum because we have a protein named Max.
>
>2. For SEARCH GENOME with a custom range list:
>
>"Genomic region coordinates, Maximum iMADS score (One line per region)"
>"Genomic region coordinates, iMADS scores for all positions in region (One line per region)” (so so max value here)
>"Genomic region coordinates, Binding site coordinates, Binding site iMADS score, Binding site >sequence (One line per site)”
>
>3. For MAKE PREDICTIONS:
>
>"Name, Sequence, Maximum iMADS score (One line per input sequence)”
>"Name, Sequence, iMADS scores for all positions (One line per input sequence)”  (so no max value here)
>"Name, Start, Stop, iMADS score (BED format; one line per binding site)”
>
>To the last option, can we add the binding site sequence?

**Comment by johnbradley** [comment]
User also requested putting the contact email on the footer of every page.

**Comment by dleehr** [comment]
Fixed in #144, except last item (Including sequence in BED) carried forward to #145
