### ISSUE TITLE
Typo in .env_sample?

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/TF-DNA-PredictionsDB#48]
The environment variables declared in [.env_sample](https://github.com/Duke-GCB/TF-DNA-PredictionsDB/blob/787f7644d7525ce95bc6dd553802531737e5bae8/.env_sample#L2) have an `_ENV` suffix:

```
DB_HOST_ENV="db"

#database name for web and db
DB_NAME_ENV="pred"
```

But [config.py](https://github.com/Duke-GCB/TF-DNA-PredictionsDB/blob/787f7644d7525ce95bc6dd553802531737e5bae8/pred/config.py#L11) that reads these variables is looking for env vars without an `_ENV` suffix:

```
DB_HOST_ENV = "DB_HOST"
...
        self.host = os.environ.get(DB_HOST_ENV, DEFAULT_DB_HOST)
```

I assume this is a typo, yes?

**Comment by johnbradley** [comment]
You are correct. Also the quotes need to be removed.
Docker doesn't seem to understand them.
Will get this fixed.
