### ISSUE TITLE
Notes from prediction worker setup

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/TF-DNA-PredictionsDB#54]
Put this in models directory: https://raw.githubusercontent.com/Duke-GCB/TrackHubGenerator/master/yaml/tracks/tracks.yaml
Put all *.model files from gordanlab cifs share gordan/Ning/TF_general/SVR/model_files_final in models.

**Comment by dleehr** [comment]
Also need models 0001 and 0002 from /gordan/josh/ning/SVR_models

And the docker image for the worker installs the latest docker client, which uses an API version currently newer than the server. Workaround for this is to set ENV variable `DOCKER_API_VERSION=1.23` for the predictions_worker service. But this needs to track with the server

**Comment by dleehr** [comment]
I think these are now captured in ansible, right? I added an issue to for some tweaks/cleanups to ansible in https://github.com/Duke-GCB/gcb-ansible/issues/13

**Comment by johnbradley** [comment]
Agreed. Closing this issue.
