### ISSUE TITLE
Fix logging for apache

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/TF-DNA-PredictionsDB#55]
When running under apache errors don't seem to be logged where I can find them.
Running 'python webserver.py' does print them out.

**Comment by dleehr** [comment]
I had this issue with d4s2, see

https://github.com/Duke-GCB/D4S2/blob/f7a8a4a8f7c714ebea804027e2e2bd929d99495e/production/d4s2.conf#L1-L3

**Comment by johnbradley** [comment]
Fixed on #120.
